- name: Comment fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^(aw1chnetapd02:/NPS/report.*)$'
    line: '#\1'
    backrefs: yes
    backup: yes


- name: Uncomment fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^#(aw1chnetapd02:/NPS/report.*)$'
    line: '\1'
    backrefs: yes
    backup: yes

- name: Remove fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^aw1chnetapd02:/NPS/report\s+'
    state: absent
    backup: yes

#Ex: current fstab:
#aw1chnetapd02:/NPS/report /oldmount nfs defaults 0 0
#fstab_entry: "aw1chnetapd02:/NPS/report /newmount nfs rw,bg,hard 0 0"
---
- name: Add entry to fstab with backup
  hosts: all
  become: yes

  vars:
    fstab_entry: "add Fstab entry"
- name: Add or update Fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^aw1chnetapd02:/NPS/report\s+'
    line: "{{ fstab_entry }}"
    state: present
